resources:
  - name: Queueify
    type: git
    source:
      branch: ((branch))
      uri: ((github_uri))
      private_key: ((private_key))

jobs:
- name: unit-test
  plan:
  - get: Queueify
    trigger: true
  - task: unit-test
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker_repo))
          tag: ((docker_repo_version))
      inputs:
      - name: Queueify
      run:
        path: Queueify/ci/tasks/test.sh